Replace client_cp_service.proto with metadata_service.proto and job_service.proto
gopay-bootcamp/octavius pull request #93
Opened 2020-09-18 04:09 UTC by vipinpahwa

**Description**
This pull request divides the client-controller services into more specific metadata services and job services. According to that, changes are done in the client and server.
for #85

2020-09-18 05:09 UTC, adbusa67 requested changes

2020-09-18 05:09 UTC, adbusa67 commented on internal/cli/client/client.go
> -	client                protobuf.ClientCPServicesClient
How about replacing `ClientCPServices` to `ClientServices` and also for `ExecutorCPServices` to `ExecutorServices` everywhere in the project ? here cp is common for both and we know that each part is connected to cp only. I guess we also discussed it in the meeting.

2020-09-18 05:17 UTC, adbusa67 commented
How about replacing `ClientCPproto` to `Clientproto` and the same for executor everywhere in the project? here cp is common for both and we know that each part is connected to cp only.

2020-09-19 04:58 UTC, littlestar642 commented
Closing since cannot move further with this.

2020-09-19 04:58 UTC, closed without merging